exports['Anyone'] = require('./anyone.js')
exports['Anyone in Voice'] = require('./voice.js')
exports['VIP'] = require('./vip.js')
exports['Owner'] = require('./owner.js')
exports['Admin'] = require('./admin.js')
